language: node_js
node_js:
  - '0.12'
sudo: false
after_success:
  - gulp coverage
deploy:
  provider: script
  script: echo "npm credentials were revoked on 2018-07-12. We regenerated many
    credentials, but this repository had no changes in at least 18 months and
    was skipped. Reconfigure npm deployments. -omsmith"; exit 1
  on:
    tags: true
